name: testing hcltm-action

on:
  push:
    branches:
      - main

jobs:
  hcltm-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hcltm validate
        uses: xntrik/hcltm-action
        with:
          command: 'validate'
          files: './hcl-files/*'
