name: hcltm validate

on: [push, pull_request]

jobs:
  hcltm-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hcltm validate
        uses: xntrik/hcltm-action@v0.0.10
        with:
          command: 'validate'
          files: './hcl-files/*'
