name: hcltm dfd

on:
  push:
    branches:
      - main

jobs:
  hcltm-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HCLTM DFD
        uses: xntrik/hcltm-action@v0.0.3
        with:
          command: 'dfd'
          files: './hcl-files/*'
          outdir: './dfd'
