name: hcltm dfd

on:
  push:
    branches:
      - main

jobs:
  hcltm-dfd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HCLTM DFD
        uses: xntrik/hcltm-action@v0.0.10
        with:
          command: 'dfd'
          files: './hcl-files/*'
          outdir: './dfd'
      - name: HCLTM DFD DOT
        uses: xntrik/hcltm-action@v0.0.10
        with:
          command: 'dfd'
          files: './hcl-files/*'
          outdir: './dfd-dot'
          dfd-type: 'dot'
      - name: HCLTM DFD SVG 
        uses: xntrik/hcltm-action@v0.0.10
        with:
          command: 'dfd'
          files: './hcl-files/*'
          outdir: './dfd-svg'
          dfd-type: 'svg'

